# Generated by Django 4.2.1 on 2023-05-25 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Contact ID')),
                ('contact', models.CharField(max_length=100, verbose_name='Fullname')),
            ],
            options={
                'verbose_name': 'CONTACT',
                'verbose_name_plural': 'CONTACTS',
                'db_table': 'CONTACT',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Phone ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Contact Phone')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='phonebook.contactmodel')),
            ],
            options={
                'verbose_name': 'PHONENUMBER',
                'verbose_name_plural': 'PHONENUMBERS',
                'db_table': 'PHONENUMBERS',
            },
        ),
        migrations.AddIndex(
            model_name='contactmodel',
            index=models.Index(fields=['id'], name='contact_id'),
        ),
        migrations.AddIndex(
            model_name='phonenumbers',
            index=models.Index(fields=['id'], name='phone_id'),
        ),
        migrations.AddIndex(
            model_name='phonenumbers',
            index=models.Index(fields=['phone'], name='contact_phone'),
        ),
    ]
