# Generated by Django 4.2.1 on 2023-05-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_alter_phonenumbers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='phone',
            field=models.CharField(max_length=255, unique=True, verbose_name='Contact Phone'),
        ),
    ]
