# Generated by Django 4.2.1 on 2023-05-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='User ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='User First name')),
                ('lastname', models.CharField(max_length=100, verbose_name='User Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='User Email')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='User Phone')),
                ('password', models.CharField(max_length=150, verbose_name='User Pass')),
                ('is_active', models.BooleanField(default=True, verbose_name='User Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='User Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='User SuperUSer')),
                ('is_driver', models.BooleanField(default=False, verbose_name='User Driver')),
                ('is_client', models.BooleanField(default=False, verbose_name='User Client')),
                ('date_join', models.DateTimeField(auto_now_add=True, verbose_name='User Create')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='User Last login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User Model',
                'verbose_name_plural': 'Users Model',
                'db_table': 'Users',
                'managed': True,
                'indexes': [models.Index(fields=['id'], name='id_user'), models.Index(fields=['phone'], name='phone_user'), models.Index(fields=['email'], name='email_user')],
            },
        ),
    ]
